<a href="https://colab.research.google.com/github/avijit7074/price_prediction_gurgaon/blob/master/capstone_flat_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import re
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [4]:
df = pd.read_csv('/content/flats - flats(1).csv')

In [5]:
df.head()

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,https://www.99acres.com/2-bhk-bedroom-apartmen...,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,https://www.99acres.com/2-bhk-bedroom-apartmen...,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,https://www.99acres.com/2-bhk-bedroom-apartmen...,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [6]:
df.shape

(3006, 20)

link column is not necessary for me . i droped it

In [7]:
df.drop(columns='link', inplace=True)
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ...",C68850746
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ...",H68850564
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ...",J68850120
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN,S68849476
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ...",L47956793

In [8]:
df.sample(5)

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
605,3 BHK Flat in Sector 83 Gurgaon,Emaar Palm Gardens4.1 ★,1.35 Crore,"₹ 12,325/sq.ft.",Super Built up area 1720(159.79 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Servant Room,"Sector 83 Gurgaon, Gurgaon, Haryana",7th of 16 Floors,South-West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",A beautiful 3 bhk apartment in sector-83 gurga...,NaN,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...","['Green Area5 out of 5', 'Construction4 out of...",O55737304
2938,3 BHK Flat in Sector 106 Gurgaon,Paras Dews,1.4 Crore,"₹ 6,000/sq.ft.",Super Built up area 1760(163.51 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,"Servant Room,Study Room,Others","Sector 106 Gurgaon, Gurgaon, Haryana",12nd of 24 Floors,NaN,Under Construction,"['Chintapurni Mandir', 'State bank ATM', 'R K ...","Best location, almost ready to move",[],NaN,NaN,L32711003
2393,2 BHK Flat in Sector 79 Gurgaon,Godrej 1014.0 ★,1.41 Crore,"₹ 9,000/sq.ft.",Carpet area: 1572 (146.04 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 79 Gurgaon, Gurgaon, Haryana",3rd of 14 Floors,NaN,0 to 1 Year Old,"['Vatika Town Square-INXT', 'Naurangpur Road',...","It's a new society, ready to move. Complementa...",NaN,"['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",J57709348
972,4 BHK Flat in Sector 106 Gurgaon,Paras Dews,1.32 Crore,"₹ 5,605/sq.ft.",Super Built up area 2355(218.79 sq.m.)Built Up...,4 Bedrooms,5 Bathrooms,3+ Balconies,Servant Room,"Sector 106 Gurgaon, Gurgaon, Haryana",11st of 24 Floors,South-West,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...","This 4 bhk flat is located in paras dews, whic...","['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Feng Shui / Vaastu Compliant', 'Security / F...",NaN,Y69429218
309,3 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,2.2 Crore,"₹ 14,202/sq.ft.",Carpet area: 1549 (143.91 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Block A 4th Floor, Smart World Orchard, Gurgao...",4th of 4 Floors,North,Within 3 months,"['Sector 55-56 Metro station', 'Bestech Centra...",Welcome to your dream home at smart world orch...,[],"['Centrally Air Conditioned', 'Water purifier'...",NaN,J69350180

in society column some society name are like 'Signature Global Solera3.7 ★' i.e.with rating. so i have to fix it

In [9]:
df['society']=df['society'].apply(lambda name: re.sub(r'\d+\.\d+\s★', '', str(name)).strip()).str.lower()

In society column two values are as 'not applicable' , '.' , 'nan' and 'nul'  . So I replaced them by the correct name manually.

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3006 entries, 0 to 3005
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3006 non-null   object
 1   society          3006 non-null   object
 2   price            3004 non-null   object
 3   area             2995 non-null   object
 4   areaWithType     3005 non-null   object
 5   bedRoom          3006 non-null   object
 6   bathroom         3006 non-null   object
 7   balcony          3006 non-null   object
 8   additionalRoom   1694 non-null   object
 9   address          3000 non-null   object
 10  floorNum         3004 non-null   object
 11  facing           2127 non-null   object
 12  agePossession    3005 non-null   object
 13  nearbyLocations  2912 non-null   object
 14  description      3006 non-null   object
 15  furnishDetails   2203 non-null   object
 16  features         2594 non-null   object
 17  rating           2674 non-null   object
 18  property_id      3006 non-null   object
dtypes: object(19)
memory usage: 446.3+ KB

In [11]:
df.loc[df[df.society=='not applicable'].index, 'society'] = 'rk homes'
df.loc[df[df.society=='.'].index, 'society'] = 'vashist properties'
df.loc[df[df.society=='nan'].index, 'society'] = 'raheja revanta'
df.loc[df[df.society=='nul'].index, 'society'] = 'vally view estate'

In [12]:
df.society.value_counts().shape

(600,)

in price column some value like 'Price on Request' so i am going to drop them ultimately they are not going to help me.

In [13]:
df.drop(df[df.price == 'Price on Request'].index, inplace = True)

in price column some value is null, and i can not fill them randomly it may produce baisness in the time of prediction. So i droped it

In [14]:
df.drop(df[df.price.isnull()].index,inplace = True)

In price column some price are in crore and some of them in lac. So i convert them in crore to maintain the same unit.

In [15]:
df['price']=df['price'].str.split(" ").apply(lambda x:float(x[0]) if x[1]=='Crore' else (float(x[0])*100000)/10000000)

I renamed the price column as 'price_in_cr'. It identifies that the values present in the column are in crore

In [16]:
df.rename(columns={'price':'price_in_cr'}, inplace=True)

In [17]:
df.sample(5)

,property_name,society,price_in_cr,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
191,3 BHK Flat in Sector 79 Gurgaon,m3m antalya hills,1.15,"₹ 7,496/sq.ft.",Super Built up area 1534(142.51 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,3+ Balconies,Study Room,"Sector 79 Gurgaon, Gurgaon, Haryana",1st of 4 Floors,NaN,Dec-25,"['Vatika Town Square-INXT Mall', 'Delhi - Jaip...",Residential apartment for sell.The property ha...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ...",R68390214
1309,2 BHK Flat in Sector 95 Gurgaon,rof ananda,0.33,₹ 60/sq.ft.,Carpet area: 54917 (5101.96 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sector 95 Gurgaon, Gurgaon, Haryana",13rd of 14 Floors,South-West,1 to 5 Year Old,"['Metro', 'Dwarka Expressway', 'Rajeev Chowk',...","Ambitious, personable agent with 15 years of e...",NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Environment4 out of 5', 'Lifestyle4.5 out of...",N70172062
1115,3 BHK Flat in Sector 84 Gurgaon,ss the coralwood,1.01,"₹ 5,771/sq.ft.",Super Built up area 1750(162.58 sq.m.)Built Up...,3 Bedrooms,3 Bathrooms,2 Balconies,NaN,"Sector 84 Gurgaon, Gurgaon, Haryana",18th of 21 Floors,North-West,1 to 5 Year Old,"['Sapphire 83 Mall', 'Sector 84 Road', 'Dwarka...",Ss the coralwood is one of the most popular de...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area4 out of 5', 'Construction4 out of...",B68616090
835,3 BHK Flat in Sector 54 Gurgaon,shree arihant apartment,1.55,"₹ 7,380/sq.ft.",Super Built up area 2100(195.1 sq.m.)Built Up ...,3 Bedrooms,3 Bathrooms,3+ Balconies,"Pooja Room,Others","Near Golf Course Rd ,sector 54 Gurgaon, Sector...",3rd of 9 Floors,North-East,5 to 10 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...",Brokers please excuse. This beautiful 3 bhk fl...,"['4 Fan', '1 Exhaust Fan', '4 Geyser', '24 Lig...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle5 out of 5...",E68958236
1530,3 BHK Flat in Sector 85 Gurgaon,ss,1.98,"₹ 8,222/sq.ft.",Super Built up area 2408(223.71 sq.m.)Built Up...,3 Bedrooms,4 Bathrooms,3 Balconies,NaN,"Sector 85 Gurgaon, Gurgaon, Haryana",6th of 14 Floors,West,1 to 5 Year Old,"['Orris Community Center', 'Indian Oil', 'Essa...",This beautiful 3 bhk flat in sector 85 gurgaon...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment5 out of 5', 'Lifestyle5 out of 5...",E70087054

Area column have this "₹ 8,450/sq.ft." kind of value. So i extracted only 8450 to easy to make the prediction

In [18]:
df['area']=df['area'].apply(lambda text:float(''.join(filter(str.isdigit, text))))

In [19]:
df.sample(5)

,property_name,society,price_in_cr,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
404,3 BHK Flat in DLF Phase 4,dlf regency park,2.35,13224.0,Super Built up area 1777(165.09 sq.m.),3 Bedrooms,3 Bathrooms,2 Balconies,Servant Room,"DLF Phase 4, Gurgaon, Haryana",18th of 21 Floors,North-East,10+ Year Old,"['Dlf phase 1 metro station', 'Sector 42-43 me...",3 bhk with the servant room is available for s...,"['5 Wardrobe', '6 Fan', '4 Geyser', '6 Light',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction5 out of...",T69621608
864,3 BHK Flat in Sector 102 Gurgaon,emaar gurgaon greens,1.49,9030.0,Super Built up area 1650(153.29 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"T-22/1002, Sector 102 Gurgaon, Gurgaon, Haryana",10th of 14 Floors,North-East,1 to 5 Year Old,"['JMS Marine Square Mall', 'Dwarka Expressway'...","Situated in sector 102 gurgaon, emaar gurgaon ...","['5 Fan', '1 Exhaust Fan', '16 Light', '4 AC',...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",K69714928
2319,4 BHK Flat in Valley View Estate,valley view estate,1.50,8278.0,Carpet area: 1812 (168.34 sq.m.),4 Bedrooms,4 Bathrooms,3+ Balconies,"Study Room,Servant Room,Others","Valley View Estate, Gurgaon, Haryana",9th of 15 Floors,North,10+ Year Old,"['HANUMAN MANDIR', 'SHIV MANDIR BALIYAWAS', 'I...",Apartment specifications: \nSize: 1812 sq ft a...,"['7 Fan', '1 Exhaust Fan', '20 Light', 'No AC'...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5...",F69492454
2532,3 BHK Flat in Sector 79 Gurgaon,mapsko mount ville,1.65,9091.0,Built Up area: 1815 (168.62 sq.m.),3 Bedrooms,3 Bathrooms,No Balcony,NaN,"Sector 79, Sector 79 Gurgaon, Gurgaon, Haryana",12nd of 12 Floors,NaN,undefined,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",Best in class property available at sector 79 ...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,"['Green Area5 out of 5', 'Construction5 out of...",S69041162
1992,2 BHK Flat in Sohna,mvn athens,0.24,4210.0,Super Built up area 570(52.95 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,1 to 5 Year Old,"['SBI ATM', 'Axis bank ATM', 'UCO bank ATM', '...",Residential apartment for sell.Located on 12th...,"['2 Wardrobe', '2 Fan', '2 Light', 'No AC', 'N...","['Power Back-up', 'Lift(s)', 'Swimming Pool', ...","['Green Area4 out of 5', 'Construction4 out of...",R70087278

Accordingly I changed "area" in "area_per_sq.ft" to clarify about the column

In [20]:
df.rename(columns={'area':'price_per_sq.ft'}, inplace = True)
#df.rename(columns={'price_per_sq.ft':'area'},inplace=True)
print('')

In [21]:
df.sample(5)

,property_name,society,price_in_cr,price_per_sq.ft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
849,4 BHK Flat in Sector 71 Gurgaon,chd avenue,1.30,5531.0,Super Built up area 2350(218.32 sq.m.),4 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Middle Floor And Lower Floor, Sector 71 Gurgao...",5th of 14 Floors,North-East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","This 4 bhk flat is located in chd avenue 71, w...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Green Area5 out of 5', 'Construction3 out of...",T69344422
933,2 BHK Flat in Sector 107 Gurgaon,m3m woodshire,0.80,5856.0,Super Built up area 1366(126.91 sq.m.)Carpet a...,2 Bedrooms,2 Bathrooms,3+ Balconies,Pooja Room,"Dwarka Expressway, Sector 107 Gurgaon, Gurgaon...",6th of 14 Floors,West,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 2 bhk spacious apartment in m3m wood...,"['4 Fan', '1 Exhaust Fan', '1 Geyser', '4 Ligh...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ...",F69544930
490,2 BHK Flat in Sector 85 Gurgaon,ss the leaf,1.09,6661.0,Super Built up area 1640(152.36 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"502, Sector 85 Gurgaon, Gurgaon, Haryana",5th of 26 Floors,North-East,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Located in sector 85 gurgaon. Spread over 11.0...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou...",M69584914
1574,2 BHK Flat in Sector 68 Gurgaon,m3m sierra 68,1.08,8674.0,Super Built up area 1245(115.66 sq.m.)Built Up...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"T-8, Sector 68 Gurgaon, Gurgaon, Haryana",1st of 15 Floors,West,1 to 5 Year Old,"['Airia Mall', 'Sohna Road', 'Golf Course Exte...","M3m sierra 68 in sector 68, gurgaon is a ready...","['2 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5...",Z69526410
478,3 BHK Flat in Sector 102 Gurgaon,conscient heritage max,1.90,9783.0,Super Built up area 1942(180.42 sq.m.),3 Bedrooms,4 Bathrooms,3+ Balconies,Servant Room,"Sector 102 Gurgaon, Gurgaon, Haryana",20th of 26 Floors,North-East,1 to 5 Year Old,"['Huda Metro Station', 'Ocus Medley Mall', 'Th...",Looking for a 3 bhk property for sale in gurga...,"['1 Geyser', 'No AC', 'No Bed', 'No Chimney', ...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area5 out of 5', 'Construction5 out of...",G69435466

I renamed bedRoom column as bedrooms, bathroom as bathrooms, balcony as balconies.

In [22]:
df.rename(columns={'bedRoom':'bedrooms', 'bathroom':'bathrooms', 'balcony':'balconies'}, inplace = True)

No null value present in the bedrooms columns

In [23]:
df['bedrooms'].isnull().sum()

0

I extracted the number of bedrooms are present and convert the column type as integer

In [24]:
df['bedrooms']=df['bedrooms'].str.split(' ').apply(lambda x: int(x[0]))

I extracted the number of bathrooms are present and convert the column type as integer

No null value present in the bathrooms columns

In [25]:
df.bathrooms.isnull().sum()

0

In [26]:
df['bathrooms']=df['bathrooms'].str.split(' ').apply(lambda x:int(x[0]))

No null value present in the balconies column

In [27]:
df.balconies.isnull().sum()

0

I extracted the number of bedrooms are present let the column type as it is. Because some value like "3+ Balconies" and it represents that in the particular flat there have more than 3 balconies.

In [28]:
df['balconies']=df['balconies'].str.split(' ').apply(lambda x:x[0])

In [29]:
df['bedrooms'].astype(int)
df['bathrooms'].astype(int)
print('')

In [30]:
df.sample(5)

,property_name,society,price_in_cr,price_per_sq.ft,areaWithType,bedrooms,bathrooms,balconies,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1520,3 BHK Flat in Sector 85 Gurgaon,ss the leaf,2.00,8305.0,Super Built up area 2408(223.71 sq.m.)Built Up...,3,4,3,Servant Room,"Sector 85 Gurgaon, Gurgaon, Haryana",6th of 14 Floors,North,1 to 5 Year Old,"['Sapphire 83 Mall', 'Dwarka Expressway', 'Cen...",Located in the popular residential address of ...,"['6 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4.5 out of 5', 'Construction4.5 ou...",S70086988
1615,3 BHK Flat in Sector 56 Gurgaon,sukhshanti apartment,1.65,7006.0,Super Built up area 2355(218.79 sq.m.),3,3,3+,Study Room,"000, Sector 56 Gurgaon, Gurgaon, Haryana",5th of 10 Floors,North,5 to 10 Year Old,"['Sector metro station', 'Sector metro station...",Brokers please excuse\n3 bhk +study room resid...,"['3 Wardrobe', '1 Water Purifier', '3 Fan', '1...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle5 out of 5...",U69297024
1168,4 BHK Flat in Sector 69 Gurgaon,tulip violet,1.75,8706.0,Super Built up area 2010(186.74 sq.m.),4,4,2,NaN,"Sector 69 Gurgaon, Gurgaon, Haryana",10th of 14 Floors,North-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",A well maintained brand new flat available on ...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Security / Fire Alarm', 'Intercom Facility',...","['Green Area5 out of 5', 'Construction4 out of...",K66588784
1457,3 BHK Flat in Sector 99A Gurgaon,pareena coban residences,1.56,7811.0,Super Built up area 1997(185.53 sq.m.),3,5,3,"Servant Room,Others","401, Sector 99A Gurgaon, Gurgaon, Haryana",4th of 20 Floors,North-East,0 to 1 Year Old,"['Gopal Super Market', 'Little Need Super Mark...",Its luxury apartment and specias fkat with 5 w...,"['5 AC', '1 Modular Kitchen', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle3 out of 5...",Z70031022
2908,3 BHK Flat in Sector 37D Gurgaon,ramprastha the atrium,1.00,7782.0,Super Built up area 1285(119.38 sq.m.),3,3,2,NaN,"Sector 37D Gurgaon, Gurgaon, Haryana",4th of 13 Floors,NaN,1 to 5 Year Old,"['Dwarka Expressway', 'Delhi Jaipur Highway', ...",Wood work in all 3 rooms. \nModular kitchen wi...,"['1 Exhaust Fan', '1 Modular Kitchen', '1 Chim...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'P...","['Management4 out of 5', 'Green Area5 out of 5...",M65536434

I introduced a new column named as "sector" from the 'address' column. Which contain in which sector the flat is present.

In [31]:
df.insert(loc=2, column = 'sector',value=df['address'].apply(lambda s: re.search(r'[Ss]ector[\s-]+\d+', str(s)).group().lower() if re.search(r'[Ss]ector[\s-]+\d+', str(s)) else "NA"))

In sector column there are 369 values are given as 'NA'.

In [32]:
df[(df.sector=='NA')].shape

(369, 20)

I created a new dataframe named as temp_df which contain only the rows where sector value is 'NA'.

In [33]:
temp_df=df[df.sector=="NA"]

I used society column to fill 'NA' value present in sector column.

In [34]:
temp_df.society.value_counts()

signature global park                         30
bestech park view residency                   23
eldeco accolade                               20
hcbs sports ville                             16
gls arawali homes                             15
the close north                               14
dlf regency park                              11
mvn athens                                    11
breez global heights                          10
breez global hill view                         9
ashiana anmol                                  6
suncity vatsal valley                          6
ashiana mulberry                               6
unitech fresco                                 5
silverglades the melia                         5
essel towers                                   5
trisara our homes 3                            4
essel tower                                    4
signature the serenas                          4
dlf carlton estate                             3
unitech heritage city                          3
paras quartier                                 3
ambience lagoon                                3
dlf royalton tower                             3
krrish provence estate                         3
suncity platinum towers                        3
dlf belvedere towers                           3
valley view estate                             3
shri ram apartments                            3
silverglades hightown residences               2
hero homes                                     2
shree shyam residency                          2
lagoon apartment                               2
my home                                        2
om appartments                                 2
sahara grace                                   2
ramprastha city                                2
samaspurkunj                                   2
apna enclave                                   2
ss residency                                   2
zara aavaas                                    2
dlf the icon                                   2
tulsiani easy in homes                         2
central park flower valley                     2
palam vihar society                            2
ganga apartment                                2
dlf city                                       2
the close south                                2
kamal residence                                1
adarsh nagar                                   1
pareena micasa                                 1
surbhi apartment                               1
g l s arawali homes                            1
the pearl apartmen                             1
ashray apartment                               1
the ivy                                        1
eden landmark                                  1
global height                                  1
ansal valley view estate                       1
krishna apartment                              1
shreeram apartment ii                          1
ansal sushant residency                        1
maa bhagwati residency                         1
ashok vihar phase 2                            1
shyam apartment                                1
sare green parc phase 3                        1
uphar lakshya homes                            1
chanderlok society                             1
sare homes                                     1
ansals api esencia                             1
ansals duplex flat                             1
shri balaji apartment                          1
aditya apartment                               1
ansal harmony homes                            1
green court                                    1
bhemerlei                                      1
divya apartments                               1
vally view estate                              1
unitech the palms                              1
rk tower                                       1
bptp amstoria                                  1
ss radiance residency                          1
smart world one                                1
bajrang apartments                             1
malibu towers                                  1
saroop garden                                  1
takshila heights sector 37 c                   1
vidya apartment                                1
palam vihar extension west zone rwa            1
maruti kunj                                    1
ansal plaza                                    1
the crew bos chs manesar                       1
dnha group housing society                     1
dlf wellington estate                          1
denso haryana housing society                  1
laxmi apartment                                1
swarn jayanti cghs                             1
dlf city plots phase 3                         1
cghs agrim apartment                           1
shyamkunj ashok vihar pahse 2                  1
m m residency, krishna colony, gurgaon         1
ganpati apartment  2, laxman vihar phase 1     1
maruti vihar colony                            1
jmd empire                                     1
malibu towne                                   1
abhinav group housing society                  1
ashiyara 2                                     1
hanumanta apartment                            1
shyam sadan                                    1
micasa sec 68                                  1
supertech araville                             1
sushant lok 1 builder floors                   1
rk homes                                       1
huda ashok vihar phase                         1
pooja apartment                                1
ompee k s residency                            1
the cocoon                                     1
ansal maple crescent                           1
dlf exclusive floors                           1
bsf chs                                        1
dlf ridgewood estate                           1
ats marigold                                   1
511 sarahah tower                              1
new colony, gurgaon                            1
dlf 3 apartment                                1
raheja maheshwara                              1
dlf the grove                                  1
floor type society                             1
surya vihar rwa                                1
dlf beverly park                               1
dlf icon                                       1
dlf 76                                         1
woodstock floors                               1
builder floor                                  1
tashee capital gateway                         1
dron apartment                                 1
new sathi apartments                           1
beverley park 1                                1
vatika lifestyle homes                         1
empire estate                                  1
professional society                           1
unitech harmony                                1
vashist properties                             1
dlf trinity towers                             1
krishna appartment                             1
Name: society, dtype: int64

I find the sector depending upon the society name and fill them manually.

In [35]:
df.loc[df[df.society=='signature global park'].index, 'sector'] = 'sector 36'
df.loc[df[df.society=='sahara grace'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='rk homes'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='vashist properties'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='bestech park view residency'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='eldeco accolade'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='hcbs sports ville'].index, 'sector'] = 'sector 35'
df.loc[df[df.society=='gls arawali homes'].index, 'sector'] = 'sector 4'
df.loc[df[df.society=='the close north'].index, 'sector'] = 'sector 50'
df.loc[df[df.society=='dlf regency park'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='mvn athens'].index, 'sector'] = 'sector 5'
df.loc[df[df.society=='breez global heights'].index, 'sector'] = 'sector 48'
df.loc[df[df.society=='breez global hill view'].index, 'sector'] = 'sector 11'
df.loc[df[df.society=='ashiana anmol'].index, 'sector'] = 'sector 33'
df.loc[df[df.society=='suncity vatsal valley'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='ashiana mulberry'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='unitech fresco'].index, 'sector'] = 'sector 50'
df.loc[df[df.society=='silverglades the melia'].index, 'sector'] = 'sector 35'
df.loc[df[df.society=='essel towers'].index, 'sector'] = 'sector 25'
df.loc[df[df.society=='trisara our homes 3'].index, 'sector'] = 'sector 6'
df.loc[df[df.society=='essel tower'].index, 'sector'] = 'sector 25'
df.loc[df[df.society=='signature the serenas'].index, 'sector'] = 'sector 36'
df.loc[df[df.society=='dlf carlton estate'].index, 'sector'] = 'sector 53'
df.loc[df[df.society=='unitech heritage city'].index, 'sector'] = 'sector 25'
df.loc[df[df.society=='paras quartier'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='ambience lagoon'].index, 'sector'] = 'sector 24'
df.loc[df[df.society=='dlf royalton tower'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='krrish provence estate'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='suncity platinum towers'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='dlf belvedere towers'].index, 'sector'] = 'sector 24'
df.loc[df[df.society=='valley view estate'].index, 'sector'] = 'sector 58'
df.loc[df[df.society=='shri ram apartments'].index, 'sector'] = 'sector 52'
df.loc[df[df.society=='silverglades hightown residences'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='hero homes'].index, 'sector'] = 'sector 104'
df.loc[df[df.society=='shree shyam residency'].index, 'sector'] = 'sector 22'
df.loc[df[df.society=='lagoon apartment'].index, 'sector'] = 'sector 24'
df.loc[df[df.society=='my home'].index, 'sector'] = 'sector 13'
df.loc[df[df.society=='om appartments'].index, 'sector'] = 'sector 112'
df.loc[df[df.society=='ramprastha city'].index, 'sector'] = 'sector 37'
df.loc[df[df.society=='samaspurkunj'].index, 'sector'] = 'sector 51'
df.loc[df[df.society=='apna enclave'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='ss residency'].index, 'sector'] = 'sector 4'
df.loc[df[df.society=='zara aavaas'].index, 'sector'] = 'sector 104'
df.loc[df[df.society=='dlf the icon'].index, 'sector'] = 'sector 53'
df.loc[df[df.society=='tulsiani easy in homes'].index, 'sector'] = 'sector 35'
df.loc[df[df.society=='central park flower valley'].index, 'sector'] = 'sector 33'
df.loc[df[df.society=='palam vihar society'].index, 'sector'] = 'sector 4'
df.loc[df[df.society=='ganga apartment'].index, 'sector'] = 'sector 13'
df.loc[df[df.society=='dlf city'].index, 'sector'] = 'sector 26'
df.loc[df[df.society=='the close south'].index, 'sector'] = 'sector 50'
df.loc[df[df.society=='kamal residence'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='adarsh nagar'].index, 'sector'] = 'sector 12'
df.loc[df[df.society=='pareena micasa'].index, 'sector'] = 'sector 68'
df.loc[df[df.society=='surbhi apartment'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='g l s arawali homes'].index, 'sector'] = 'sector 4'
df.loc[df[df.society=='the pearl apartmen'].index, 'sector'] = 'sector 41'
df.loc[df[df.society=='ashray apartment'].index, 'sector'] = 'sector 10'
df.loc[df[df.society=='the ivy'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='eden landmark'].index, 'sector'] = 'sector 102'
df.loc[df[df.society=='global height'].index, 'sector'] = 'sector 33'
df.loc[df[df.society=='ansal valley view estate'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='krishna apartment'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='shreeram apartment ii'].index, 'sector'] = 'sector 110'
df.loc[df[df.society=='ansal sushant residency'].index, 'sector'] = 'sector 57'
df.loc[df[df.society=='maa bhagwati residency'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='ashok vihar phase 2'].index, 'sector'] = 'sector 5'
df.loc[df[df.society=='shyam apartment'].index, 'sector'] = 'sector 11'
df.loc[df[df.society=='sare green parc phase 3'].index, 'sector'] = 'sector 92'
df.loc[df[df.society=='uphar lakshya homes'].index, 'sector'] = 'sector 105'
df.loc[df[df.society=='chanderlok society'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='sare homes'].index, 'sector'] = 'sector 92'
df.loc[df[df.society=='ansals api esencia'].index, 'sector'] = 'sector 67'
df.loc[df[df.society=='ansals duplex flat'].index, 'sector'] = 'sector 86'
df.loc[df[df.society=='shri balaji apartment'].index, 'sector'] = 'sector 33'
df.loc[df[df.society=='aditya apartment'].index, 'sector'] = 'sector 86'
df.loc[df[df.society=='ansal harmony homes'].index, 'sector'] = 'sector 57'
df.loc[df[df.society=='green court'].index, 'sector'] = 'sector 90'
df.loc[df[df.society=='bhemerlei'].index, 'sector'] = 'sector 6'
df.loc[df[df.society=='divya apartments'].index, 'sector'] = 'sector 56'
df.loc[df[df.society=='nul'].index, 'sector'] = 'sector 5'
df.loc[df[df.society=='unitech the palms'].index, 'sector'] = 'sector 41'
df.loc[df[df.society=='rk tower'].index, 'sector'] = 'sector 14'
df.loc[df[df.society=='bptp amstoria'].index, 'sector'] = 'sector 102'
df.loc[df[df.society=='ss radiance residency'].index, 'sector'] = 'sector 49'
df.loc[df[df.society=='smart world one'].index, 'sector'] = 'sector 113'
df.loc[df[df.society=='bajrang apartments'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='malibu towers'].index, 'sector'] = 'sector 47'
df.loc[df[df.society=='saroop garden'].index, 'sector'] = 'sector 105'
df.loc[df[df.society=='takshila heights sector 37 c'].index, 'sector'] = 'sector 37'
df.loc[df[df.society=='vidya apartment'].index, 'sector'] = 'sector 56'
df.loc[df[df.society=='palam vihar extension west zone rwa'].index, 'sector'] = 'sector 2'
df.loc[df[df.society=='maruti kunj'].index, 'sector'] = 'sector 67'
df.loc[df[df.society=='ansal plaza'].index, 'sector'] = 'sector 23'
df.loc[df[df.society=='the crew bos chs manesar'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='dnha group housing society'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='dlf wellington estate'].index, 'sector'] = 'sector 53'
df.loc[df[df.society=='denso haryana housing society'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='laxmi apartment'].index, 'sector'] = 'sector 99'
df.loc[df[df.society=='swarn jayanti cghs'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='dlf city plots phase 3'].index, 'sector'] = 'sector 24'
df.loc[df[df.society=='cghs agrim apartment'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='shyamkunj ashok vihar pahse 2'].index, 'sector'] = 'sector 5'
df.loc[df[df.society=='m m residency, krishna colony, gurgaon'].index, 'sector'] = 'sector 7'
df.loc[df[df.society=='ganpati apartment  2, laxman vihar phase 1'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='maruti vihar colony'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='jmd empire'].index, 'sector'] = 'sector 62'
df.loc[df[df.society=='malibu towne'].index, 'sector'] = 'sector 47'
df.loc[df[df.society=='abhinav group housing society'].index, 'sector'] = 'sector 9'
df.loc[df[df.society=='ashiyara 2'].index, 'sector'] = 'sector 37'
df.loc[df[df.society=='hanumanta apartment'].index, 'sector'] = 'sector 33'
df.loc[df[df.society=='shyam sadan'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='micasa sec 68'].index, 'sector'] = 'sector 68'
df.loc[df[df.society=='sushant lok 1 builder floors'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='supertech araville'].index, 'sector'] = 'sector 79'
df.loc[df[df.society=='huda ashok vihar phase'].index, 'sector'] = 'sector 5'
df.loc[df[df.society=='pooja apartment'].index, 'sector'] = 'sector 3'
df.loc[df[df.society=='ompee k s residency'].index, 'sector'] = 'sector 110'
df.loc[df[df.society=='the cocoon'].index, 'sector'] = 'sector 26'
df.loc[df[df.society=='ansal maple crescent'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='dlf exclusive floors'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='bsf chs'].index, 'sector'] = 'sector 89'
df.loc[df[df.society=='dlf ridgewood estate'].index, 'sector'] = 'sector 27'
df.loc[df[df.society=='ats marigold'].index, 'sector'] = 'sector 89'
df.loc[df[df.society=='511 sarahah tower'].index, 'sector'] = 'sector 12'
df.loc[df[df.society=='new colony, gurgaon'].index, 'sector'] = 'sector 7'
df.loc[df[df.society=='dlf 3 apartment'].index, 'sector'] = 'sector 53'
df.loc[df[df.society=='raheja maheshwara'].index, 'sector'] = 'sector 11'
df.loc[df[df.society=='dlf the grove'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='floor type society'].index, 'sector'] = 'sector 76'
df.loc[df[df.society=='surya vihar rwa'].index, 'sector'] = 'sector 21'
df.loc[df[df.society=='dlf beverly park'].index, 'sector'] = 'sector 25'
df.loc[df[df.society=='dlf icon'].index, 'sector'] = 'sector 43'
df.loc[df[df.society=='dlf 76'].index, 'sector'] = 'sector 76'
df.loc[df[df.society=='woodstock floors'].index, 'sector'] = 'sector 50'
df.loc[df[df.society=='builder floor'].index, 'sector'] = 'sector 106'
df.loc[df[df.society=='tashee capital gateway'].index, 'sector'] = 'sector 111'
df.loc[df[df.society=='dron apartment'].index, 'sector'] = 'sector 15'
df.loc[df[df.society=='new sathi apartments'].index, 'sector'] = 'sector 54'
df.loc[df[df.society=='beverley park 1'].index, 'sector'] = 'sector 28'
df.loc[df[df.society=='vatika lifestyle homes'].index, 'sector'] = 'sector 83'
df.loc[df[df.society=='empire estate'].index, 'sector'] = 'sector 39'
df.loc[df[df.society=='professional society'].index, 'sector'] = 'sector 1'
df.loc[df[df.society=='unitech harmony'].index, 'sector'] = 'sector 50'
df.loc[df[df.society=='dlf trinity towers'].index, 'sector'] = 'sector 53'
df.loc[df[df.society=='krishna appartment'].index, 'sector'] = 'sector 54'

Now I do not have any "NA" value in the sector column. So I cleaned the sector column.

In [36]:
df[df.sector=="NA"].shape[0]

1

### ADDITIONAL ROOM

In the additionalRoom column there are 1303 null values.

In [37]:
df['additionalRoom'].isnull().sum()

1303

I filled the null values present in the additionalRoom column by 'not applicable'. So that the column does not contain any null value.

In [38]:
df['additionalRoom']=df['additionalRoom'].apply(lambda x:'not applicable' if pd.isna(x) else x)

### FLOOR NUMBER

floorNum column contain two null values. So we have to fill them.

In [39]:
df.floorNum.isnull().sum()

2

The floor num is given in the address column for both the rows 181 and 2764

In [40]:
df.loc[181, 'floorNum'] = '6th floor'
df.loc[2764, 'floorNum'] = '2th floor'

I want to extract only the floor number. There have somme abnormal value like 'Ground', 'Lower' and 'Basement'.

In [41]:
df['floorNum'].str.split(" ")

0               [4th  , of, 4, Floors]
1               [1st  , of, 3, Floors]
2             [12nd  , of, 14, Floors]
3               [2nd  , of, 4, Floors]
4               [5th  , of, 8, Floors]
5               [3rd  , of, 3, Floors]
6              [5th  , of, 25, Floors]
7             [14th  , of, 27, Floors]
8               [2nd  , of, 3, Floors]
9             [31st  , of, 40, Floors]
10              [1st  , of, 4, Floors]
11             [4th  , of, 13, Floors]
12             [4th  , of, 15, Floors]
13             [3rd  , of, 20, Floors]
14            [13rd  , of, 13, Floors]
15            [25th  , of, 25, Floors]
16             [Ground, of, 1, Floors]
17            [Ground, of, 14, Floors]
19            [12nd  , of, 13, Floors]
20              [4th  , of, 4, Floors]
21            [11st  , of, 22, Floors]
22              [4th  , of, 4, Floors]
23            [Ground, of, 14, Floors]
24            [10th  , of, 25, Floors]
26              [3rd  , of, 3, Floors]
27            [20th  , of, 20, Floors]
28             [5th  , of, 17, Floors]
29             [4th  , of, 12, Floors]
30              [4th  , of, 4, Floors]
31              [1st  , of, 4, Floors]
32            [12nd  , of, 12, Floors]
33             [8th  , of, 12, Floors]
34            [20th  , of, 20, Floors]
35              [8th  , of, 8, Floors]
36            [21st  , of, 24, Floors]
37            [Ground, of, 11, Floors]
38             [6th  , of, 19, Floors]
39             [1st  , of, 19, Floors]
40              [1st  , of, 3, Floors]
41            [12nd  , of, 17, Floors]
42             [6th  , of, 24, Floors]
43             [1st  , of, 25, Floors]
44              [2nd  , of, 4, Floors]
45              [1st  , of, 4, Floors]
46             [9th  , of, 29, Floors]
47              [5th  , of, 8, Floors]
48            [18th  , of, 32, Floors]
49            [29th  , of, 31, Floors]
50              [3rd  , of, 5, Floors]
51             [3rd  , of, 26, Floors]
52             [5th  , of, 18, Floors]
53              [1st  , of, 4, Floors]
54             [9th  , of, 12, Floors]
55             [6th  , of, 10, Floors]
56              [2nd  , of, 4, Floors]
57            [14th  , of, 14, Floors]
58             [1st  , of, 11, Floors]
59             [8th  , of, 14, Floors]
60              [2nd  , of, 2, Floors]
61            [12nd  , of, 12, Floors]
62             [4th  , of, 14, Floors]
63             [1st  , of, 18, Floors]
64             [7th  , of, 19, Floors]
65              [3rd  , of, 4, Floors]
66             [5th  , of, 20, Floors]
67             [9th  , of, 15, Floors]
68            [14th  , of, 17, Floors]
69            [14th  , of, 14, Floors]
70            [15th  , of, 20, Floors]
71             [6th  , of, 14, Floors]
72             [6th  , of, 14, Floors]
73             [2nd  , of, 12, Floors]
74             [3rd  , of, 11, Floors]
75              [2nd  , of, 4, Floors]
76             [4th  , of, 13, Floors]
77              [3rd  , of, 4, Floors]
78             [6th  , of, 14, Floors]
79             [8th  , of, 13, Floors]
80              [2nd  , of, 4, Floors]
81              [4th  , of, 4, Floors]
82            [Ground, of, 14, Floors]
83            [11st  , of, 11, Floors]
84              [1st  , of, 3, Floors]
85            [11st  , of, 13, Floors]
86            [21st  , of, 41, Floors]
87             [4th  , of, 13, Floors]
88              [2nd  , of, 5, Floors]
89              [2nd  , of, 3, Floors]
90              [4th  , of, 4, Floors]
91            [32nd  , of, 32, Floors]
92              [2nd  , of, 4, Floors]
93              [2nd  , of, 2, Floors]
94              [2nd  , of, 2, Floors]
95            [11st  , of, 11, Floors]
96            [23rd  , of, 26, Floors]
97             [6th  , of, 12, Floors]
98             [9th  , of, 20, Floors]
99              [1st  , of, 4, Floors]
100            [5th  , of, 15, Floors]
101             [43  , of, 47, Floors]
102             [1st  , of, 1, Floors]
103             [1st  , of, 4, Floors]
104            [1st  , of, 13, Floors]
105           [11st  , of, 12, Floors]
106           [14th  , of, 24, Floors]
107            [9th  , of, 30, Floors]
108            [8th  , of, 14, Floors]
109             [9th  , of, 9, Floors]
110            [2nd  , of, 12, Floors]
111            [4th  , of, 14, Floors]
112           [32nd  , of, 55, Floors]
113             [43  , of, 47, Floors]
114            [2nd  , of, 19, Floors]
115             [3rd  , of, 4, Floors]
116            [8th  , of, 22, Floors]
117             [3rd  , of, 4, Floors]
118           [20th  , of, 32, Floors]
119            [2nd  , of, 17, Floors]
120         [Basement, of, 28, Floors]
121            [4th  , of, 10, Floors]
122            [Ground, of, 4, Floors]
123             [3rd  , of, 4, Floors]
124             [4th  , of, 8, Floors]
125             [3rd  , of, 4, Floors]
126            [6th  , of, 20, Floors]
127           [13rd  , of, 13, Floors]
128           [13rd  , of, 13, Floors]
129           [16th  , of, 16, Floors]
130             [3rd  , of, 4, Floors]
131            [Ground, of, 1, Floors]
132           [11st  , of, 14, Floors]
133            [2nd  , of, 14, Floors]
134           [12nd  , of, 12, Floors]
135             [2nd  , of, 4, Floors]
136            [1st  , of, 18, Floors]
137            [4th  , of, 12, Floors]
138           [11st  , of, 13, Floors]
139            [5th  , of, 17, Floors]
140            [1st  , of, 25, Floors]
141           [12nd  , of, 16, Floors]
142           [16th  , of, 18, Floors]
143             [6th  , of, 6, Floors]
144             [2nd  , of, 2, Floors]
145             [3rd  , of, 4, Floors]
146           [11st  , of, 25, Floors]
147           [10th  , of, 18, Floors]
148            [2nd  , of, 25, Floors]
149             [4th  , of, 4, Floors]
150           [19th  , of, 41, Floors]
151             [1st  , of, 3, Floors]
152             [8th  , of, 8, Floors]
153           [18th  , of, 19, Floors]
154           [10th  , of, 16, Floors]
155            [7th  , of, 20, Floors]
156            [2nd  , of, 14, Floors]
157           [10th  , of, 10, Floors]
158            [5th  , of, 12, Floors]
159           [10th  , of, 20, Floors]
160           [20th  , of, 34, Floors]
161           [20th  , of, 22, Floors]
162             [3rd  , of, 4, Floors]
163           [13rd  , of, 14, Floors]
164            [3rd  , of, 19, Floors]
165            [7th  , of, 18, Floors]
166             [4th  , of, 4, Floors]
167            [4th  , of, 14, Floors]
168             [2nd  , of, 4, Floors]
169            [2nd  , of, 25, Floors]
170            [4th  , of, 14, Floors]
171            [3rd  , of, 19, Floors]
172             [1st  , of, 1, Floors]
173             [2nd  , of, 4, Floors]
174           [11st  , of, 15, Floors]
175           [11st  , of, 21, Floors]
176           [16th  , of, 22, Floors]
177            [8th  , of, 10, Floors]
178            [1st  , of, 35, Floors]
179           [18th  , of, 25, Floors]
180            [8th  , of, 15, Floors]
181                       [6th, floor]
182            [2nd  , of, 16, Floors]
183           [17th  , of, 17, Floors]
184           [23rd  , of, 28, Floors]
185           [10th  , of, 18, Floors]
186           [30th  , of, 32, Floors]
187             [4th  , of, 4, Floors]
188             [2nd  , of, 3, Floors]
189            [Ground, of, 3, Floors]
190           [Ground, of, 14, Floors]
191             [1st  , of, 4, Floors]
192             [1st  , of, 1, Floors]
193           [11st  , of, 36, Floors]
194           [11st  , of, 13, Floors]
195            [Ground, of, 3, Floors]
196           [19th  , of, 19, Floors]
197           [28th  , of, 28, Floors]
198             [4th  , of, 4, Floors]
199             [9th  , of, 9, Floors]
200             [7th  , of, 7, Floors]
201          [Basement, of, 4, Floors]
202           [15th  , of, 15, Floors]
203            [2nd  , of, 34, Floors]
204           [Ground, of, 14, Floors]
205            [9th  , of, 10, Floors]
206            [1st  , of, 15, Floors]
207             [1st  , of, 1, Floors]
208            [4th  , of, 34, Floors]
209            [4th  , of, 18, Floors]
210            [3rd  , of, 15, Floors]
211             [1st  , of, 4, Floors]
212            [1st  , of, 19, Floors]
213     [Lower, Ground, of, 4, Floors]
214           [13rd  , of, 13, Floors]
215            [4th  , of, 40, Floors]
216            [6th  , of, 18, Floors]
217           [20th  , of, 47, Floors]
218           [27th  , of, 48, Floors]
219             [6th  , of, 7, Floors]
220           [33rd  , of, 48, Floors]
221           [35th  , of, 35, Floors]
222           [26th  , of, 47, Floors]
223            [Ground, of, 1, Floors]
224             [2nd  , of, 4, Floors]
225            [4th  , of, 14, Floors]
226           [10th  , of, 17, Floors]
227           [11st  , of, 14, Floors]
228           [10th  , of, 22, Floors]
229           [Ground, of, 24, Floors]
230            [3rd  , of, 12, Floors]
231            [7th  , of, 25, Floors]
232            [8th  , of, 14, Floors]
233             [2nd  , of, 4, Floors]
234            [3rd  , of, 18, Floors]
235             [1st  , of, 4, Floors]
236            [9th  , of, 14, Floors]
237           [14th  , of, 15, Floors]
238             [4th  , of, 4, Floors]
239            [8th  , of, 25, Floors]
240           [10th  , of, 14, Floors]
241            [3rd  , of, 14, Floors]
242             [3rd  , of, 4, Floors]
243             [2nd  , of, 4, Floors]
244            [3rd  , of, 14, Floors]
245             [7th  , of, 7, Floors]
246             [2nd  , of, 4, Floors]
247            [3rd  , of, 15, Floors]
248            [8th  , of, 34, Floors]
249           [12nd  , of, 14, Floors]
250            [8th  , of, 42, Floors]
251             [1st  , of, 4, Floors]
252            [1st  , of, 22, Floors]
253           [26th  , of, 34, Floors]
254           [21st  , of, 29, Floors]
255            [8th  , of, 32, Floors]
256            [2nd  , of, 14, Floors]
257            [1st  , of, 12, Floors]
258             [2nd  , of, 4, Floors]
259           [39th  , of, 40, Floors]
260            [1st  , of, 14, Floors]
261            [8th  , of, 10, Floors]
262             [2nd  , of, 3, Floors]
263             [3rd  , of, 4, Floors]
264             [7th  , of, 9, Floors]
265            [4th  , of, 15, Floors]
266           [22nd  , of, 24, Floors]
267           [14th  , of, 20, Floors]
268           [11st  , of, 15, Floors]
269           [17th  , of, 17, Floors]
270            [3rd  , of, 12, Floors]
271           [12nd  , of, 13, Floors]
272            [8th  , of, 19, Floors]
273            [3rd  , of, 14, Floors]
274           [14th  , of, 14, Floors]
275             [7th  , of, 7, Floors]
276            [9th  , of, 15, Floors]
277            [2nd  , of, 17, Floors]
278             [3rd  , of, 3, Floors]
279             [6th  , of, 6, Floors]
280           [16th  , of, 16, Floors]
281           [12nd  , of, 12, Floors]
282             [1st  , of, 1, Floors]
283             [4th  , of, 4, Floors]
284           [17th  , of, 17, Floors]
285            [7th  , of, 26, Floors]
286           [11st  , of, 30, Floors]
287             [4th  , of, 8, Floors]
288            [1st  , of, 14, Floors]
289            [6th  , of, 14, Floors]
290             [1st  , of, 3, Floors]
291           [17th  , of, 17, Floors]
292             [1st  , of, 7, Floors]
293           [16th  , of, 18, Floors]
294           [19th  , of, 40, Floors]
295           [31st  , of, 32, Floors]
296           [14th  , of, 22, Floors]
297            [5th  , of, 19, Floors]
298             [2nd  , of, 4, Floors]
299             [1st  , of, 4, Floors]
300            [1st  , of, 10, Floors]
301           [15th  , of, 32, Floors]
302             [1st  , of, 7, Floors]
303             [1st  , of, 2, Floors]
304             [2nd  , of, 3, Floors]
305           [11st  , of, 14, Floors]
306            [9th  , of, 26, Floors]
307           [33rd  , of, 42, Floors]
308           [14th  , of, 18, Floors]
309             [4th  , of, 4, Floors]
310            [5th  , of, 14, Floors]
311           [18th  , of, 18, Floors]
312            [1st  , of, 14, Floors]
313           [20th  , of, 23, Floors]
314            [9th  , of, 14, Floors]
315           [18th  , of, 19, Floors]
316            [8th  , of, 32, Floors]
317            [4th  , of, 15, Floors]
318            [9th  , of, 17, Floors]
319             [4th  , of, 8, Floors]
320            [1st  , of, 14, Floors]
321            [6th  , of, 14, Floors]
322             [1st  , of, 3, Floors]
323           [19th  , of, 40, Floors]
324           [31st  , of, 32, Floors]
325            [5th  , of, 19, Floors]
326             [1st  , of, 4, Floors]
327            [1st  , of, 10, Floors]
328           [15th  , of, 32, Floors]
329             [1st  , of, 7, Floors]
330             [1st  , of, 2, Floors]
331             [2nd  , of, 3, Floors]
332           [11st  , of, 14, Floors]
333            [9th  , of, 26, Floors]
334           [14th  , of, 18, Floors]
335            [5th  , of, 14, Floors]
336            [1st  , of, 14, Floors]
337            [9th  , of, 14, Floors]
338           [18th  , of, 19, Floors]
339            [4th  , of, 15, Floors]
340            [1st  , of, 44, Floors]
341           [20th  , of, 20, Floors]
342           [24th  , of, 31, Floors]
343            [2nd  , of, 15, Floors]
344             [4th  , of, 4, Floors]
345           [14th  , of, 14, Floors]
346            [9th  , of, 16, Floors]
347           [14th  , of, 15, Floors]
348            [4th  , of, 14, Floors]
349           [26th  , of, 30, Floors]
350            [2nd  , of, 16, Floors]
351           [14th  , of, 24, Floors]
352           [17th  , of, 17, Floors]
353            [2nd  , of, 14, Floors]
354           [25th  , of, 25, Floors]
355            [9th  , of, 22, Floors]
356             [4th  , of, 4, Floors]
357            [6th  , of, 17, Floors]
358            [5th  , of, 14, Floors]
359            [4th  , of, 14, Floors]
360           [14th  , of, 21, Floors]
361           [15th  , of, 19, Floors]
362            [7th  , of, 14, Floors]
363             [2nd  , of, 4, Floors]
364           [16th  , of, 20, Floors]
365           [24th  , of, 51, Floors]
366           [10th  , of, 20, Floors]
367             [2nd  , of, 4, Floors]
368            [2nd  , of, 12, Floors]
369            [2nd  , of, 24, Floors]
370            [1st  , of, 19, Floors]
371            [8th  , of, 18, Floors]
372           [12nd  , of, 22, Floors]
373           [18th  , of, 19, Floors]
374             [1st  , of, 4, Floors]
375            [2nd  , of, 36, Floors]
376             [3rd  , of, 4, Floors]
377           [11st  , of, 11, Floors]
378            [7th  , of, 20, Floors]
379            [5th  , of, 18, Floors]
380            [6th  , of, 12, Floors]
381           [19th  , of, 31, Floors]
382           [25th  , of, 25, Floors]
383           [10th  , of, 10, Floors]
384           [10th  , of, 10, Floors]
385             [3rd  , of, 9, Floors]
386            [8th  , of, 14, Floors]
387            [5th  , of, 12, Floors]
388            [4th  , of, 22, Floors]
389            [1st  , of, 35, Floors]
390           [10th  , of, 14, Floors]
391           [16th  , of, 24, Floors]
392           [10th  , of, 14, Floors]
393             [3rd  , of, 8, Floors]
394           [17th  , of, 19, Floors]
395            [9th  , of, 14, Floors]
396           [11st  , of, 26, Floors]
397           [19th  , of, 20, Floors]
398           [Ground, of, 16, Floors]
399           [Ground, of, 23, Floors]
400            [8th  , of, 26, Floors]
401            [4th  , of, 11, Floors]
402           [30th  , of, 32, Floors]
403           [16th  , of, 51, Floors]
404           [18th  , of, 21, Floors]
405            [2nd  , of, 10, Floors]
406            [7th  , of, 10, Floors]
407             [2nd  , of, 4, Floors]
408           [10th  , of, 10, Floors]
409            [9th  , of, 12, Floors]
410            [6th  , of, 10, Floors]
411           [14th  , of, 29, Floors]
412           [25th  , of, 36, Floors]
413            [7th  , of, 23, Floors]
414            [4th  , of, 14, Floors]
415             [7th  , of, 9, Floors]
416           [18th  , of, 32, Floors]
417           [12nd  , of, 17, Floors]
418             [3rd  , of, 4, Floors]
419           [21st  , of, 28, Floors]
420           [14th  , of, 28, Floors]
421            [5th  , of, 25, Floors]
422            [3rd  , of, 19, Floors]
423           [19th  , of, 24, Floors]
424           [10th  , of, 14, Floors]
425             [5th  , of, 9, Floors]
426           [10th  , of, 30, Floors]
427            [7th  , of, 14, Floors]
428           [11st  , of, 20, Floors]
429            [2nd  , of, 17, Floors]
430             [2nd  , of, 4, Floors]
431            [7th  , of, 14, Floors]
432            [6th  , of, 14, Floors]
433           [11st  , of, 17, Floors]
434            [9th  , of, 14, Floors]
435             [4th  , of, 4, Floors]
436           [14th  , of, 20, Floors]
437             [5th  , of, 5, Floors]
438             [1st  , of, 4, Floors]
439           [16th  , of, 27, Floors]
440            [1st  , of, 10, Floors]
441           [18th  , of, 32, Floors]
442            [6th  , of, 16, Floors]
443            [8th  , of, 13, Floors]
444             [4th  , of, 4, Floors]
445            [7th  , of, 27, Floors]
446             [9th  , of, 9, Floors]
447             [3rd  , of, 4, Floors]
448           [11st  , of, 18, Floors]
449           [17th  , of, 25, Floors]
450            [7th  , of, 42, Floors]
451            [5th  , of, 30, Floors]
452           [16th  , of, 32, Floors]
453            [2nd  , of, 16, Floors]
454            [8th  , of, 29, Floors]
455             [2nd  , of, 8, Floors]
456            [3rd  , of, 32, Floors]
457            [6th  , of, 26, Floors]
458           [Ground, of, 14, Floors]
459            [2nd  , of, 12, Floors]
460           [15th  , of, 40, Floors]
461           [10th  , of, 25, Floors]
462           [11st  , of, 30, Floors]
463           [10th  , of, 15, Floors]
464            [4th  , of, 12, Floors]
465            [3rd  , of, 18, Floors]
466            [9th  , of, 19, Floors]
467            [8th  , of, 16, Floors]
468            [7th  , of, 12, Floors]
469            [5th  , of, 12, Floors]
470            [7th  , of, 14, Floors]
471            [7th  , of, 14, Floors]
472            [9th  , of, 14, Floors]
473            [2nd  , of, 20, Floors]
474            [5th  , of, 18, Floors]
475           [11st  , of, 20, Floors]
476            [8th  , of, 11, Floors]
477            [7th  , of, 17, Floors]
478           [20th  , of, 26, Floors]
479           [10th  , of, 12, Floors]
480            [7th  , of, 29, Floors]
481           [10th  , of, 51, Floors]
482           [16th  , of, 21, Floors]
483            [8th  , of, 21, Floors]
484            [1st  , of, 14, Floors]
485           [18th  , of, 30, Floors]
486           [15th  , of, 30, Floors]
487           [25th  , of, 30, Floors]
488            [5th  , of, 29, Floors]
489            [9th  , of, 26, Floors]
490            [5th  , of, 26, Floors]
491            [7th  , of, 26, Floors]
492            [7th  , of, 26, Floors]
493            [7th  , of, 26, Floors]
494           [12nd  , of, 30, Floors]
495            [5th  , of, 15, Floors]
496            [4th  , of, 10, Floors]
497            [6th  , of, 10, Floors]
498             [3rd  , of, 6, Floors]
499           [10th  , of, 18, Floors]
500           [15th  , of, 28, Floors]
501           [15th  , of, 28, Floors]
502           [10th  , of, 14, Floors]
503            [9th  , of, 28, Floors]
504           [10th  , of, 15, Floors]
505           [10th  , of, 21, Floors]
506            [9th  , of, 12, Floors]
507            [Ground, of, 4, Floors]
508             [1st  , of, 2, Floors]
509           [11st  , of, 12, Floors]
510           [17th  , of, 24, Floors]
511            [1st  , of, 26, Floors]
512           [Ground, of, 18, Floors]
513            [7th  , of, 14, Floors]

I replaced Groud as 0, Lower as 0 and Basement as -1 and extract only the floor number.

In [42]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [43]:
df.sample(5)

,property_name,society,sector,price_in_cr,price_per_sq.ft,areaWithType,bedrooms,bathrooms,balconies,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
1302,3 BHK Flat in Sector 83 Gurgaon,emaar palm gardens,sector 83,1.75,9210.0,Super Built up area 1900(176.52 sq.m.)Built Up...,3,3,3,Servant Room,"804, Sector 83 Gurgaon, Gurgaon, Haryana",6,West,1 to 5 Year Old,"[""V'Lante Mall"", 'NH 48 Gurugram', 'iGrow Mont...",This 3 bhk apartment is available for sale in ...,"['3 Wardrobe', '8 Fan', '1 Exhaust Fan', '1 St...","['Water purifier', 'Security / Fire Alarm', 'F...","['Green Area5 out of 5', 'Construction4 out of...",V69525180
685,4 BHK Flat in Sector 85 Gurgaon,orris aster court premier,sector 85,1.49,5820.0,Super Built up area 2560(237.83 sq.m.)Built Up...,4,5,3+,Servant Room,"Sector 85 Gurgaon, Gurgaon, Haryana",10,East,1 to 5 Year Old,"['Propose Metro Station', 'SS Omnia Mall', 'Na...",Looking for a 4 bhk property for sale in gurga...,"['1 Stove', '5 AC', '1 Chimney', '1 Modular Ki...","['Lift(s)', 'Maintenance Staff', 'Water Storag...","['Environment5 out of 5', 'Lifestyle5 out of 5...",G69158602
2710,4 BHK Flat in Sector 52 Gurgaon,ardee city,sector 52,1.55,7381.0,Built Up area: 2100 (195.1 sq.m.)Carpet area: ...,4,4,3,not applicable,"Sector 52, Sector 52 Gurgaon, Gurgaon, Haryana",1,NaN,5 to 10 Year Old,NaN,Best in class property available at sector 52 ...,"['1 Wardrobe', '1 Fan', '1 Light', 'No AC', 'N...",NaN,"['Green Area4 out of 5', 'Amenities4 out of 5'...",Y68863904
1724,4 BHK Flat in Sector 69 Gurgaon,tulip violet,sector 69,2.00,9583.0,Super Built up area 2087(193.89 sq.m.),4,4,2,not applicable,"002, Sector 69 Gurgaon, Gurgaon, Haryana",0,South-East,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",Ground floor with extended balcony this 4 bhk ...,"['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Water purifier', 'Security / Fire Alarm', 'P...","['Green Area5 out of 5', 'Construction4 out of...",A69721704
1274,2 BHK Flat in Sector 62 Gurgaon,emaar digihomes,sector 62,2.10,13925.0,Super Built up area 1508(140.1 sq.m.)Built Up ...,2,2,3,Others,"Sector 62 Gurgaon, Gurgaon, Haryana",12,North-East,0 to 1 Year Old,"['Sector 55-56 Metro Station', 'Omaxe Gurgaon ...",Located in the popular residential address of ...,"['6 Wardrobe', '3 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle5 out of 5...",V70088016

### FACING

In facing column there are 873 null values.

In [44]:
df.facing.isnull().sum()

873

I filled the missing values by 'NA' and put the others same.

In [45]:
df['facing']=df['facing'].apply(lambda x:'NA' if pd.isna(x) else x)

## PROPERTY ID column is not going to help me anyway. So i droped it.

In [46]:
df.drop(columns='property_id', inplace=True)

FEATURE ENGINEERING

Creating a new column as 'total_area' with the help of 'price_in_cr' and	'price_per_sq.ft' columns.

In [47]:
df.insert(loc=5, column='total_area', value=round(df['price_in_cr']*10000000/df['price_per_sq.ft'],2))

In [48]:
df.sample(5)

,property_name,society,sector,price_in_cr,price_per_sq.ft,total_area,areaWithType,bedrooms,bathrooms,balconies,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
2377,3 BHK Flat in Sector 56 Gurgaon,cghs vidya enclave,sector 56,1.7000,10967.0,1550.10,Super Built up area 1600(148.64 sq.m.)Carpet a...,3,2,3,Store Room,"Sector 56 Gurgaon, Gurgaon, Haryana",6,NA,10+ Year Old,"['Sector metro station', 'Sector metro station...","Details:\nHigher floor, furnished with wooden ...","['1 Fan', '1 Light', '1 AC', 'No Bed', 'No Chi...","['Private Garden / Terrace', 'Intercom Facilit...","['Green Area5 out of 5', 'Construction4.5 out ..."
1875,2 BHK Flat in Sector 81 Gurgaon,bestech park view ananda,sector-81,0.8699,7951.0,1094.08,Super Built up area 1360(126.35 sq.m.)Built Up...,2,2,3,not applicable,"Sector-81, Sector 81 Gurgaon, Gurgaon, Haryana",8,West,1 to 5 Year Old,"['Metro Station Kankrola sec 87', 'Sapphire 83...",1360 sqft front tower 8th floor semi furnished...,"['2 Wardrobe', '4 Fan', '1 Exhaust Fan', '2 Ge...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction5 out of..."
1083,4 BHK Flat in Sector 69 Gurgaon,tulip violet,sector 69,1.8000,8955.0,2010.05,Super Built up area 2010(186.74 sq.m.),4,4,2,Pooja Room,"A7 908, Sector 69 Gurgaon, Gurgaon, Haryana",9,South-West,1 to 5 Year Old,"['Airia Mall Sector 68', 'Southern Peripheral ...",This 4 bhk apartment is available for sale in ...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of..."
2003,3 BHK Flat in Sector 70 Gurgaon,tulip orange,sector 70,1.0000,10309.0,970.03,Carpet area: 970 (90.12 sq.m.),3,2,2,not applicable,"Sector 70 Gurgaon, Gurgaon, Haryana",3,NA,5 to 10 Year Old,"['Sector 55-56 Metro Station', 'Reach 3 Roads'...","Sun facing, overlooking park, play area for kids","['3 Wardrobe', '3 Fan', '1 Modular Kitchen', '...","['Feng Shui / Vaastu Compliant', 'Lift(s)', 'S...","['Green Area4 out of 5', 'Construction4 out of..."
2366,2 BHK Flat in Sector 89 Gurgaon,smart world gems,sector 89,1.0000,9033.0,1107.05,Carpet area: 1107 (102.84 sq.m.),2,2,2,Study Room,"J56, Sector 89 Gurgaon, Gurgaon, Haryana",1,NA,By 2025,"['Sant Soordas Sihi Metro Station', 'Airia Mal...",Smartworld gems floor with car parking possess...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

INTRODUCING another column name as 'proper_type'.

In [49]:
df.insert(loc=1, column='property_type', value='flat')

In [50]:
df.sample(5)

,property_name,property_type,society,sector,price_in_cr,price_per_sq.ft,total_area,areaWithType,bedrooms,bathrooms,balconies,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1468,4 BHK Flat in Sector 110 Gurgaon,flat,indiabulls enigma,sector 110,3.60,10588.0,3400.08,Super Built up area 3400(315.87 sq.m.),4,5,3,Servant Room,"Sector 110 Gurgaon, Gurgaon, Haryana",7,North,1 to 5 Year Old,"['Dwarka Sector 21 Metro Station', 'Gurgaon Dr...",This 4 bhk flat is located in indiabulls enigm...,"['1 Modular Kitchen', '8 AC', 'No Bed', 'No Ch...","['Water purifier', 'Security / Fire Alarm', 'P...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1180,3 BHK Flat in Sector 102 Gurgaon,flat,shapoorji pallonji joyville gurugram,sector 102,2.15,12706.0,1692.11,Super Built up area 1692(157.19 sq.m.)Built Up...,3,3,3,not applicable,"Sector 102 Gurgaon, Gurgaon, Haryana",10,South-West,1 to 5 Year Old,"['Khan Market', 'The Esplanade Mall', 'Dwarka ...",Located in the popular residential address of ...,"['2 Wardrobe', '1 Exhaust Fan', '1 Geyser', '1...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area4 out of 5', 'Construction5 out of..."
2952,2 BHK Flat in Sector 90 Gurgaon,flat,green court,sector 90,0.40,6389.0,626.08,Super Built up area 626(58.16 sq.m.)Carpet are...,2,2,1,not applicable,"L-808, Sector 90 Gurgaon, Gurgaon, Haryana",8,South,0 to 1 Year Old,"['Baba Kanala Chowk', 'Pataudi Rd', 'Gurukul P...","Proposed metro station, on dwarka express way,...",NaN,"['Feng Shui / Vaastu Compliant', 'Lift(s)', 'P...","['Management4 out of 5', 'Green Area3 out of 5..."
1295,3 BHK Flat in Sector 80 Gurgaon,flat,godrej frontier,sector 80,1.40,6189.0,2262.08,Super Built up area 2262(210.15 sq.m.)Built Up...,3,4,2,"Pooja Room,Store Room","123, Sector 80 Gurgaon, Gurgaon, Haryana",10,North-West,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",3 bhk 2262 sqft available for sell in godrej f...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area4 out of 5', 'Construction4 out of..."
757,4 BHK Flat in DLF Phase 5,flat,dlf the icon,sector 53,5.25,20388.0,2575.04,Super Built up area 2575(239.23 sq.m.)Built Up...,4,4,3,"Servant Room,Others,Pooja Room","Dlf The Icon, DLF Phase 5, Gurgaon, Haryana",9,North,10+ Year Old,"['Sector 42-43 Rapid Metro Station', 'Ardee Ma...",Dlf icon all sizes avaible at best price in th...,"['4 Wardrobe', '6 Fan', '6 Light', 'No AC', 'N...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Green Area5 out of 5', 'Construction3 out of..."

In [51]:
df.to_csv('gurgaon_flat_csv_1', index=False)